/**
 * Extra search terms (Korean + English synonyms) per tool id, used to boost
 * discoverability in the command palette — so typing "jpg" finds the image
 * converter even though that word isn't in the title.
 */
export const TOOL_ALIASES: Record<string, string> = {
    "image-converter": "jpg png webp avif heic 포맷 변환 확장자 이미지",
    "image-compressor": "압축 용량 줄이기 최적화 compress optimize",
    "image-resizer": "크기 조절 리사이즈 가로 세로 resize dimensions",
    "image-cropper": "자르기 크롭 잘라내기 crop trim",
    "images-to-ppt": "ppt 슬라이드 프레젠테이션 발표 powerpoint pptx 슬라이드쇼",
    "collage-maker": "콜라주 모아 붙이기 그리드 collage grid",
    "background-remover": "배경 제거 누끼 투명 remove background transparent",
    "image-eraser": "지우기 객체 제거 인페인팅 erase remove object",
    "image-watermark": "워터마크 로고 watermark stamp",
    "ico-converter": "아이콘 파비콘 favicon ico icon",
    "favicon-generator": "파비콘 favicon icon 사이트 아이콘",
    "pdf-merge": "pdf 합치기 병합 합병 merge combine",
    "pdf-split": "pdf 분할 나누기 쪼개기 split extract",
    "pdf-to-image": "pdf 이미지 변환 png jpg 추출 to image",
    "markdown-to-pdf": "마크다운 md pdf 변환 markdown",
    "qr-generator": "qr 큐알 코드 바코드 qrcode",
    "json-formatter": "json 정렬 포맷 예쁘게 beautify format",
    "json-yaml-converter": "json yaml 변환 convert",
    "regex-tester": "정규식 정규표현식 regex regexp 패턴 test",
    "jwt-debugger": "jwt 토큰 디코드 token decode",
    "base64-converter": "base64 인코딩 디코딩 encode decode",
    "hash-generator": "해시 md5 sha sha256 hash 체크섬",
    "uuid-generator": "uuid guid 고유 아이디 식별자",
    "password-generator": "비밀번호 패스워드 암호 생성 password random",
    "color-picker": "색상 컬러 피커 hex rgb color",
    "color-palette": "팔레트 색 조합 배색 palette scheme",
    "css-gradient-generator": "그라데이션 gradient css 배경",
    "loan-calculator": "대출 이자 원리금 상환 loan mortgage",
    "tip-calculator": "팁 봉사료 tip gratuity",
    "split-bill-calculator": "더치페이 정산 1/n 나누기 split bill",
    "discount-calculator": "할인 세일 가격 discount sale",
    "percentage-calculator": "퍼센트 비율 percent percentage",
    "unit-converter": "단위 변환 길이 무게 unit convert",
    "d-day-calculator": "디데이 dday 디-데이 남은 날짜 countdown",
    "age-calculator": "나이 만나이 생일 age birthday",
    "word-counter": "글자수 단어수 원고지 character count word",
    "text-diff": "텍스트 비교 차이 diff compare",
}
