import {
  Music,
  Database,
  Ruler,
  FileJson,
  Regex,
  Clock,
  MonitorPlay,
  Presentation,
  GraduationCap,
  Receipt,
  Video,
  Image as ImageIcon,
  Sparkles,
  Zap,
  Search,
  Globe,
  FileCode,
  Terminal,
  QrCode,
  Wand2,
  Link,
  Minimize2,
  Maximize,
  FileText,
  Files,
  Calculator,
  ShieldEllipsis,
  Box,
  ScanText,
  Layers,
  Fingerprint,
  Braces,
  FilePlus2,
  Scissors,
  FileImage,
  Lock,
  KeyRound,
  Hash,
  LockKeyhole,
  BadgeCheck,
  Key,
  GitCompareArrows,
  Type,
  CaseSensitive,
  Dices,
  Shield,
  Timer,
  Tags,
  Bot,
  Map as MapIcon,
  Palette,
  Network,
  ListFilter,
  Radio,
  FileCode2,
  Activity,
  Webhook,
  Camera,
  Scaling,
  Shrink,
  MonitorSmartphone,
  Volume2,
  Globe2,
  Droplets,
  SlidersHorizontal,
  LayoutGrid,
  Smile,
  Pipette,
  FileDown,
  Table,
  Code2,
  TimerReset,
  CalendarDays,
  Thermometer,
  Eraser,
  Crop,
  Languages,
  PenTool,
  Users,
  CarFront,
  Pilcrow,
  GitBranch,
  Spline,
  Contrast,
  Proportions,
  Repeat,
  Cpu,
  Settings,
  Package,
  GitCommit,
  TrendingUp,
  FileKey,
  SpellCheck,
  Link2,
  AlignHorizontalSpaceBetween,
  Wifi,
  ListTree,
  Binary,
  Eye,
  ScanBarcode,
  Share2,
  CalendarClock,
  Film,
  AudioLines,
  FileAudio,
  RotateCw,
  Gauge,
  Combine,
  Rewind,
  VolumeX,
  Images,
  Home
} from "lucide-react";
import { YouTubeIcon } from "@/components/icons/youtube-icon";

export const toolsCatalog = [
  {
    id: "text-diff",
    titleKey: "Catalog.TextDiff.title",
    descriptionKey: "Catalog.TextDiff.description",
    icon: GitCompareArrows,
    href: "/tools/text-diff",
    color: "text-orange-500",
    tags: ["Text"],
  },
  {
    id: "word-counter",
    titleKey: "Catalog.WordCounter.title",
    descriptionKey: "Catalog.WordCounter.description",
    icon: Type,
    href: "/tools/word-counter",
    color: "text-emerald-500",
    tags: ["Text"],
  },
  {
    id: "list-sorter",
    titleKey: "Catalog.ListSorter.title",
    descriptionKey: "Catalog.ListSorter.description",
    icon: ListFilter,
    href: "/tools/list-sorter",
    color: "text-sky-500",
    tags: ["Text"],
  },
  {
    id: "morse-converter",
    titleKey: "Catalog.MorseConverter.title",
    descriptionKey: "Catalog.MorseConverter.description",
    icon: Radio,
    href: "/tools/morse-converter",
    color: "text-rose-500",
    tags: ["Text"],
  },
  {
    id: "loan-calculator",
    titleKey: "Catalog.LoanCalculator.title",
    descriptionKey: "Catalog.LoanCalculator.description",
    icon: Calculator,
    href: "/tools/loan-calculator",
    color: "text-emerald-500",
    tags: ["Utilities"],
  },
  {
    id: "text-similarity",
    titleKey: "Catalog.TextSimilarity.title",
    descriptionKey: "Catalog.TextSimilarity.description",
    icon: GitCompareArrows,
    href: "/tools/text-similarity",
    color: "text-indigo-500",
    tags: ["Text"],
  },
  {
    id: "time-zone-converter",
    titleKey: "Catalog.TimeZoneConverter.title",
    descriptionKey: "Catalog.TimeZoneConverter.description",
    icon: Globe2,
    href: "/tools/time-zone-converter",
    color: "text-sky-500",
    tags: ["Utilities"],
  },
  {
    id: "age-calculator",
    titleKey: "Catalog.AgeCalculator.title",
    descriptionKey: "Catalog.AgeCalculator.description",
    icon: TimerReset,
    href: "/tools/age-calculator",
    color: "text-pink-500",
    tags: ["Utilities"],
  },
  {
    id: "ovulation-calculator",
    titleKey: "Catalog.OvulationCalculator.title",
    descriptionKey: "Catalog.OvulationCalculator.description",
    icon: Droplets,
    href: "/tools/ovulation-calculator",
    color: "text-rose-500",
    tags: ["Utilities"],
  },
  {
    id: "bmi-calculator",
    titleKey: "Catalog.BmiCalculator.title",
    descriptionKey: "Catalog.BmiCalculator.description",
    icon: Activity,
    href: "/tools/bmi-calculator",
    color: "text-sky-500",
    tags: ["Utilities"],
  },
  {
    id: "tip-calculator",
    titleKey: "Catalog.TipCalculator.title",
    descriptionKey: "Catalog.TipCalculator.description",
    icon: Calculator,
    href: "/tools/tip-calculator",
    color: "text-emerald-500",
    tags: ["Utilities"],
  },
  {
    id: "date-calculator",
    titleKey: "Catalog.DateCalculator.title",
    descriptionKey: "Catalog.DateCalculator.description",
    icon: Clock,
    href: "/tools/date-calculator",
    color: "text-amber-500",
    tags: ["Utilities"],
  },
  {
    id: "d-day-calculator",
    titleKey: "Catalog.DDayCalculator.title",
    descriptionKey: "Catalog.DDayCalculator.description",
    icon: CalendarDays,
    href: "/tools/d-day-calculator",
    color: "text-indigo-500",
    tags: ["Utilities"],
  },
  {
    id: "percentage-calculator",
    titleKey: "Catalog.PercentageCalculator.title",
    descriptionKey: "Catalog.PercentageCalculator.description",
    icon: Calculator,
    href: "/tools/percentage-calculator",
    color: "text-emerald-500",
    tags: ["Utilities"],
  },
  {
    id: "discount-calculator",
    titleKey: "Catalog.DiscountCalculator.title",
    descriptionKey: "Catalog.DiscountCalculator.description",
    icon: Tags,
    href: "/tools/discount-calculator",
    color: "text-rose-500",
    tags: ["Utilities"],
  },
  {
    id: "split-bill-calculator",
    titleKey: "Catalog.SplitBillCalculator.title",
    descriptionKey: "Catalog.SplitBillCalculator.description",
    icon: Users,
    href: "/tools/split-bill-calculator",
    color: "text-sky-500",
    tags: ["Utilities"],
  },
  {
    id: "water-intake-calculator",
    titleKey: "Catalog.WaterIntakeCalculator.title",
    descriptionKey: "Catalog.WaterIntakeCalculator.description",
    icon: Droplets,
    href: "/tools/water-intake-calculator",
    color: "text-cyan-500",
    tags: ["Utilities"],
  },
  {
    id: "calorie-calculator",
    titleKey: "Catalog.CalorieCalculator.title",
    descriptionKey: "Catalog.CalorieCalculator.description",
    icon: Activity,
    href: "/tools/calorie-calculator",
    color: "text-orange-500",
    tags: ["Utilities"],
  },
  {
    id: "compound-interest-calculator",
    titleKey: "Catalog.CompoundInterestCalculator.title",
    descriptionKey: "Catalog.CompoundInterestCalculator.description",
    icon: Calculator,
    href: "/tools/compound-interest-calculator",
    color: "text-emerald-500",
    tags: ["Utilities"],
  },
  {
    id: "temperature-converter",
    titleKey: "Catalog.TemperatureConverter.title",
    descriptionKey: "Catalog.TemperatureConverter.description",
    icon: Thermometer,
    href: "/tools/temperature-converter",
    color: "text-sky-500",
    tags: ["Utilities"],
  },
  {
    id: "body-fat-calculator",
    titleKey: "Catalog.BodyFatCalculator.title",
    descriptionKey: "Catalog.BodyFatCalculator.description",
    icon: Activity,
    href: "/tools/body-fat-calculator",
    color: "text-amber-500",
    tags: ["Utilities"],
  },
  {
    id: "fuel-cost-calculator",
    titleKey: "Catalog.FuelCostCalculator.title",
    descriptionKey: "Catalog.FuelCostCalculator.description",
    icon: CarFront,
    href: "/tools/fuel-cost-calculator",
    color: "text-emerald-500",
    tags: ["Utilities"],
  },
  {
    id: "file-size-converter",
    titleKey: "Catalog.FileSizeConverter.title",
    descriptionKey: "Catalog.FileSizeConverter.description",
    icon: Files,
    href: "/tools/file-size-converter",
    color: "text-sky-500",
    tags: ["Utilities"],
  },
  {
    id: "sleep-calculator",
    titleKey: "Catalog.SleepCalculator.title",
    descriptionKey: "Catalog.SleepCalculator.description",
    icon: Timer,
    href: "/tools/sleep-calculator",
    color: "text-violet-500",
    tags: ["Utilities"],
  },
  {
    id: "random-picker",
    titleKey: "Catalog.RandomPicker.title",
    descriptionKey: "Catalog.RandomPicker.description",
    icon: Dices,
    href: "/tools/random-picker",
    color: "text-violet-500",
    tags: ["Utilities"],
  },
  {
    id: "string-case-converter",
    titleKey: "Catalog.StringCaseConverter.title",
    descriptionKey: "Catalog.StringCaseConverter.description",
    icon: CaseSensitive,
    href: "/tools/string-case-converter",
    color: "text-indigo-500",
    tags: ["Text"],
  },
  {
    id: "json-to-types",
    titleKey: "Catalog.JsonToTypes.title",
    descriptionKey: "Catalog.JsonToTypes.description",
    icon: FileJson,
    href: "/tools/json-to-types",
    color: "text-amber-500",
    tags: ["Data"],
  },
  {
    id: "curl-to-code",
    titleKey: "Catalog.CurlToCode.title",
    descriptionKey: "Catalog.CurlToCode.description",
    icon: Terminal,
    href: "/tools/curl-to-code",
    color: "text-blue-500",
    tags: ["Development"],
  },
  {
    id: "html-to-jsx",
    titleKey: "Catalog.HtmlToJsx.title",
    descriptionKey: "Catalog.HtmlToJsx.description",
    icon: FileCode,
    href: "/tools/html-to-jsx",
    color: "text-orange-500",
    tags: ["Development"],
  },
  {
    id: "html-entity-encoder",
    titleKey: "Catalog.HtmlEntityEncoder.title",
    descriptionKey: "Catalog.HtmlEntityEncoder.description",
    icon: Braces,
    href: "/tools/html-entity-encoder",
    color: "text-rose-500",
    tags: ["Web"],
  },
  {
    id: "number-base-converter",
    titleKey: "Catalog.NumberBaseConverter.title",
    descriptionKey: "Catalog.NumberBaseConverter.description",
    icon: Hash,
    href: "/tools/number-base-converter",
    color: "text-violet-500",
    tags: ["Data"],
  },
  {
    id: "yaml-converter",
    titleKey: "Catalog.YamlConverter.title",
    descriptionKey: "Catalog.YamlConverter.description",
    icon: FileJson,
    href: "/tools/yaml-converter",
    color: "text-teal-500",
    tags: ["Data"],
  },
  {
    id: "torrent-history",
    titleKey: "Catalog.TorrentHistory.title",
    descriptionKey: "Catalog.TorrentHistory.description",
    icon: Fingerprint,
    href: "/tools/torrent-history",
    color: "text-red-600",
    tags: ["Security"],
  },
  {
    id: "passphrase-generator",
    titleKey: "Catalog.PassphraseGenerator.title",
    descriptionKey: "Catalog.PassphraseGenerator.description",
    icon: KeyRound,
    href: "/tools/passphrase-generator",
    color: "text-blue-600",
    tags: ["Security"],
  },
  {
    id: "password-strength",
    titleKey: "Catalog.PasswordStrength.title",
    descriptionKey: "Catalog.PasswordStrength.description",
    icon: ShieldEllipsis,
    href: "/tools/password-strength",
    color: "text-emerald-600",
    tags: ["Security"],
  },
  {
    id: "security-tools",
    titleKey: "Catalog.SecurityTools.title",
    descriptionKey: "Catalog.SecurityTools.description",
    icon: Shield,
    href: "/tools/security-tools",
    color: "text-emerald-500",
    tags: ["Security"],
  },

  {
    id: "background-remover",
    titleKey: "Catalog.BackgroundRemover.title",
    descriptionKey: "Catalog.BackgroundRemover.description",
    icon: Wand2,
    href: "/tools/background-remover",
    color: "text-purple-500",
    tags: ["Image", "AI"],
  },
  {
    id: "banner-generator",
    titleKey: "Catalog.BannerGenerator.title",
    descriptionKey: "Catalog.BannerGenerator.description",
    icon: Terminal,
    href: "/tools/banner-generator",
    color: "text-orange-500",
    tags: ["Text"],
  },
  {
    id: "base64-converter",
    titleKey: "Catalog.Base64Converter.title",
    descriptionKey: "Catalog.Base64Converter.description",
    icon: FileCode,
    href: "/tools/base64-converter",
    color: "text-emerald-600",
    tags: ["Data"],
  },
  {
    id: "base64-image",
    titleKey: "Catalog.Base64Image.title",
    descriptionKey: "Catalog.Base64Image.description",
    icon: ImageIcon,
    href: "/tools/base64-image",
    color: "text-purple-500",
    tags: ["Image"],
  },
  {
    id: "border-radius-generator",
    titleKey: "Catalog.BorderRadiusGenerator.title",
    descriptionKey: "Catalog.BorderRadiusGenerator.description",
    icon: Maximize,
    href: "/tools/border-radius-generator",
    color: "text-green-500",
    tags: ["Design"],
  },
  {
    id: "box-shadow-generator",
    titleKey: "Catalog.BoxShadowGenerator.title",
    descriptionKey: "Catalog.BoxShadowGenerator.description",
    icon: Layers,
    href: "/tools/box-shadow-generator",
    color: "text-indigo-500",
    tags: ["Design"],
  },
  {
    id: "browser-info",
    titleKey: "Catalog.BrowserInfo.title",
    descriptionKey: "Catalog.BrowserInfo.description",
    icon: MonitorPlay,
    href: "/tools/browser-info",
    color: "text-blue-500",
    tags: ["Utilities"],
  },
  {
    id: "color-palette",
    titleKey: "Catalog.ColorPalette.title",
    descriptionKey: "Catalog.ColorPalette.description",
    icon: Sparkles,
    href: "/tools/color-palette",
    color: "text-pink-500",
    tags: ["Design"],
  },
  {
    id: "color-name-finder",
    titleKey: "Catalog.ColorNameFinder.title",
    descriptionKey: "Catalog.ColorNameFinder.description",
    icon: Palette,
    href: "/tools/color-name-finder",
    color: "text-fuchsia-500",
    tags: ["Design"],
  },
  {
    id: "ico-converter",
    titleKey: "Catalog.IcoConverter.title",
    descriptionKey: "Catalog.IcoConverter.description",
    icon: FileImage,
    href: "/tools/ico-converter",
    color: "text-orange-500",
    tags: ["Design"],
  },
  {
    id: "cron-generator",
    titleKey: "Catalog.CronGenerator.title",
    descriptionKey: "Catalog.CronGenerator.description",
    icon: Clock,
    href: "/tools/cron-generator",
    color: "text-yellow-500",
    tags: ["Development"],
  },
  {
    id: "favicon-generator",
    titleKey: "Catalog.FaviconGenerator.title",
    descriptionKey: "Catalog.FaviconGenerator.description",
    icon: Files,
    href: "/tools/favicon-generator",
    color: "text-indigo-500",
    tags: ["Design"],
  },
  {
    id: "glassmorphism",
    titleKey: "Catalog.Glassmorphism.title",
    descriptionKey: "Catalog.Glassmorphism.description",
    icon: Layers,
    href: "/tools/glassmorphism",
    color: "text-sky-500",
    tags: ["Design"],
  },
  {
    id: "css-pattern",
    titleKey: "Catalog.CssPattern.title",
    descriptionKey: "Catalog.CssPattern.description",
    icon: LayoutGrid,
    href: "/tools/css-pattern",
    color: "text-amber-500",
    tags: ["Design"],
  },
  {
    id: "css-gradient-generator",
    titleKey: "Catalog.GradientGenerator.title",
    descriptionKey: "Catalog.GradientGenerator.description",
    icon: Sparkles,
    href: "/tools/css-gradient-generator",
    color: "text-blue-500",
    tags: ["Design"],
  },
  {
    id: "image-compressor",
    titleKey: "Catalog.ImageCompressor.title",
    descriptionKey: "Catalog.ImageCompressor.description",
    icon: Minimize2,
    href: "/tools/image-compressor",
    color: "text-purple-500",
    tags: ["Image"],
  },
  {
    id: "image-cropper",
    titleKey: "Catalog.ImageCropper.title",
    descriptionKey: "Catalog.ImageCropper.description",
    icon: Crop,
    href: "/tools/image-cropper",
    color: "text-cyan-500",
    tags: ["Image"],
  },
  {
    id: "image-converter",
    titleKey: "Catalog.ImageConverter.title",
    descriptionKey: "Catalog.ImageConverter.description",
    icon: ImageIcon,
    href: "/tools/image-converter",
    color: "text-emerald-500",
    tags: ["Image"],
  },
  {
    id: "ocr",
    titleKey: "Catalog.OcrTool.title",
    descriptionKey: "Catalog.OcrTool.description",
    icon: ScanText,
    href: "/tools/ocr",
    color: "text-blue-500",
    tags: ["Utilities"],
  },
  {
    id: "json-yaml-converter",
    titleKey: "Catalog.JsonYaml.title",
    descriptionKey: "Catalog.JsonYaml.description",
    icon: FileJson,
    href: "/tools/json-yaml-converter",
    color: "text-emerald-600",
    tags: ["Data"],
  },
  {
    id: "json-formatter",
    titleKey: "Catalog.JsonFormatter.title",
    descriptionKey: "Catalog.JsonFormatter.description",
    icon: Braces,
    href: "/tools/json-formatter",
    color: "text-amber-500",
    tags: ["Data"],
  },
  {
    id: "json-diff",
    titleKey: "Catalog.JsonDiff.title",
    descriptionKey: "Catalog.JsonDiff.description",
    icon: FileJson,
    href: "/tools/json-diff",
    color: "text-rose-500",
    tags: ["Data"],
  },
  {
    id: "jwt-debugger",
    titleKey: "Catalog.JwtDebugger.title",
    descriptionKey: "Catalog.JwtDebugger.description",
    icon: KeyRound,
    href: "/tools/jwt-debugger",
    color: "text-violet-500",
    tags: ["Security"],
  },
  {
    id: "regex-tester",
    titleKey: "Catalog.RegexTester.title",
    descriptionKey: "Catalog.RegexTester.description",
    icon: Regex,
    href: "/tools/regex-tester",
    color: "text-indigo-500",
    tags: ["Development"],
  },
  {
    id: "my-ip",
    titleKey: "Catalog.MyIp.title",
    descriptionKey: "Catalog.MyIp.description",
    icon: Globe,
    href: "/tools/my-ip",
    color: "text-sky-500",
    tags: ["Utilities"],
  },
  {
    id: "port-scanner",
    titleKey: "Catalog.PortScanner.title",
    descriptionKey: "Catalog.PortScanner.description",
    icon: Search,
    href: "/tools/port-scanner",
    color: "text-orange-500",
    tags: ["Security"],
  },
  {
    id: "qr-generator",
    titleKey: "Catalog.QrGenerator.title",
    descriptionKey: "Catalog.QrGenerator.description",
    icon: QrCode,
    href: "/tools/qr-generator",
    color: "text-green-600",
    tags: ["Utilities"],
  },
  {
    id: "sql-converter",
    titleKey: "Catalog.SqlConverter.title",
    descriptionKey: "Catalog.SqlConverter.description",
    icon: Database,
    href: "/tools/sql-converter",
    color: "text-blue-600",
    tags: ["Data"],
  },
  {
    id: "sql-formatter",
    titleKey: "Catalog.SqlFormatter.title",
    descriptionKey: "Catalog.SqlFormatter.description",
    icon: Database,
    href: "/tools/sql-formatter",
    color: "text-blue-500",
    tags: ["Data"],
  },
  {
    id: "speed-test",
    titleKey: "Catalog.SpeedTest.title",
    descriptionKey: "Catalog.SpeedTest.description",
    icon: Zap,
    href: "/tools/speed-test",
    color: "text-yellow-500",
    tags: ["Utilities"],
  },
  {
    id: "suno-downloader",
    titleKey: "Catalog.SunoDownloader.title",
    descriptionKey: "Catalog.SunoDownloader.description",
    icon: Music,
    href: "/tools/suno-downloader",
    color: "text-pink-500",
    tags: ["Audio"],
  },
  {
    id: "svg-to-jsx",
    titleKey: "Catalog.SvgToJsx.title",
    descriptionKey: "Catalog.SvgToJsx.description",
    icon: FileCode,
    href: "/tools/svg-to-jsx",
    color: "text-indigo-500",
    tags: ["Development"],
  },
  {
    id: "unit-converter",
    titleKey: "Catalog.UnitConverter.title",
    descriptionKey: "Catalog.UnitConverter.description",
    icon: Ruler,
    href: "/tools/unit-converter",
    color: "text-emerald-500",
    tags: ["Utilities"],
  },
  {
    id: "url-converter",
    titleKey: "Catalog.UrlConverter.title",
    descriptionKey: "Catalog.UrlConverter.description",
    icon: Link,
    href: "/tools/url-converter",
    color: "text-cyan-500",
    tags: ["Web"],
  },
  {
    id: "video-converter",
    titleKey: "Catalog.VideoConverter.title",
    descriptionKey: "Catalog.VideoConverter.description",
    icon: Video,
    href: "/tools/video-converter",
    color: "text-rose-500",
    tags: ["Video"],
  },
  {
    id: "data-tools",
    titleKey: "Catalog.DataTools.title",
    descriptionKey: "Catalog.DataTools.description",
    icon: Database,
    href: "/tools/data-tools",
    color: "text-blue-600",
    tags: ["Data"],
  },
  {
    id: "text-tools",
    titleKey: "Catalog.TextTools.title",
    descriptionKey: "Catalog.TextTools.description",
    icon: ScanText,
    href: "/tools/text-tools",
    color: "text-emerald-600",
    tags: ["Text"],
  },
  {
    id: "k-series",
    titleKey: "Catalog.KSeries.title",
    descriptionKey: "Catalog.KSeries.description",
    icon: Languages,
    href: "/tools/k-series",
    color: "text-blue-600",
    tags: ["Text", "Korea"],
  },
  {
    id: "dev-tools",
    titleKey: "Catalog.DevTools.title",
    descriptionKey: "Catalog.DevTools.description",
    icon: Terminal,
    href: "/tools/dev-tools",
    color: "text-orange-500",
    tags: ["Development"],
  },
  {
    id: "hwp-viewer",
    titleKey: "Catalog.HwpViewer.title",
    descriptionKey: "Catalog.HwpViewer.description",
    icon: FileText,
    href: "/tools/hwp-viewer",
    color: "text-blue-600",
    tags: ["Utilities"],
  },
  {
    id: "markdown-preview",
    titleKey: "Catalog.MarkdownPreview.title",
    descriptionKey: "Catalog.MarkdownPreview.description",
    icon: FileText,
    href: "/tools/markdown-preview",
    color: "text-slate-500",
    tags: ["Utilities"],
  },
  {
    id: "xml-formatter",
    titleKey: "Catalog.XmlFormatter.title",
    descriptionKey: "Catalog.XmlFormatter.description",
    icon: FileCode,
    href: "/tools/xml-formatter",
    color: "text-indigo-500",
    tags: ["Data"],
  },

  {
    id: "pdf-merge",
    titleKey: "Catalog.PdfMerge.title",
    descriptionKey: "Catalog.PdfMerge.description",
    icon: FilePlus2,
    href: "/tools/pdf-merge",
    color: "text-red-500",
    tags: ["Utilities"],
  },
  {
    id: "pdf-split",
    titleKey: "Catalog.PdfSplit.title",
    descriptionKey: "Catalog.PdfSplit.description",
    icon: Scissors,
    href: "/tools/pdf-split",
    color: "text-orange-500",
    tags: ["Utilities"],
  },
  {
    id: "pdf-to-image",
    titleKey: "Catalog.PdfToImage.title",
    descriptionKey: "Catalog.PdfToImage.description",
    icon: FileImage,
    href: "/tools/pdf-to-image",
    color: "text-amber-500",
    tags: ["Utilities"],
  },
  {
    id: "image-to-pdf",
    titleKey: "Catalog.ImageToPdf.title",
    descriptionKey: "Catalog.ImageToPdf.description",
    icon: FileImage,
    href: "/tools/image-to-pdf",
    color: "text-rose-500",
    tags: ["Image"],
  },
  {
    id: "gpa-calculator",
    titleKey: "Catalog.GpaCalculator.title",
    descriptionKey: "Catalog.GpaCalculator.description",
    icon: GraduationCap,
    href: "/tools/gpa-calculator",
    color: "text-indigo-500",
    tags: ["Utilities"],
  },
  {
    id: "vat-calculator",
    titleKey: "Catalog.VatCalculator.title",
    descriptionKey: "Catalog.VatCalculator.description",
    icon: Receipt,
    href: "/tools/vat-calculator",
    color: "text-emerald-500",
    tags: ["Utilities"],
  },
  {
    id: "chmod-calculator",
    titleKey: "Catalog.ChmodCalculator.title",
    descriptionKey: "Catalog.ChmodCalculator.description",
    icon: FileKey,
    href: "/tools/chmod-calculator",
    color: "text-emerald-500",
    tags: ["Development"],
  },
  {
    id: "number-to-words",
    titleKey: "Catalog.NumberToWords.title",
    descriptionKey: "Catalog.NumberToWords.description",
    icon: SpellCheck,
    href: "/tools/number-to-words",
    color: "text-cyan-500",
    tags: ["Utilities"],
  },
  {
    id: "slug-generator",
    titleKey: "Catalog.SlugGenerator.title",
    descriptionKey: "Catalog.SlugGenerator.description",
    icon: Link2,
    href: "/tools/slug-generator",
    color: "text-sky-500",
    tags: ["Web"],
  },
  {
    id: "neumorphism-generator",
    titleKey: "Catalog.NeumorphismGenerator.title",
    descriptionKey: "Catalog.NeumorphismGenerator.description",
    icon: Box,
    href: "/tools/neumorphism-generator",
    color: "text-slate-500",
    tags: ["Design"],
  },
  {
    id: "signature-pad",
    titleKey: "Catalog.SignaturePad.title",
    descriptionKey: "Catalog.SignaturePad.description",
    icon: PenTool,
    href: "/tools/signature-pad",
    color: "text-violet-500",
    tags: ["Utilities"],
  },
  {
    id: "flexbox-generator",
    titleKey: "Catalog.FlexboxGenerator.title",
    descriptionKey: "Catalog.FlexboxGenerator.description",
    icon: AlignHorizontalSpaceBetween,
    href: "/tools/flexbox-generator",
    color: "text-indigo-500",
    tags: ["Design"],
  },
  {
    id: "css-animation-generator",
    titleKey: "Catalog.CssAnimationGenerator.title",
    descriptionKey: "Catalog.CssAnimationGenerator.description",
    icon: Sparkles,
    href: "/tools/css-animation-generator",
    color: "text-pink-500",
    tags: ["Design"],
  },
  {
    id: "ascii-table",
    titleKey: "Catalog.AsciiTable.title",
    descriptionKey: "Catalog.AsciiTable.description",
    icon: Table,
    href: "/tools/ascii-table",
    color: "text-slate-500",
    tags: ["Development"],
  },
  {
    id: "wifi-qr-generator",
    titleKey: "Catalog.WifiQrGenerator.title",
    descriptionKey: "Catalog.WifiQrGenerator.description",
    icon: Wifi,
    href: "/tools/wifi-qr-generator",
    color: "text-cyan-500",
    tags: ["Utilities"],
  },
  {
    id: "text-cleaner",
    titleKey: "Catalog.TextCleaner.title",
    descriptionKey: "Catalog.TextCleaner.description",
    icon: Eraser,
    href: "/tools/text-cleaner",
    color: "text-violet-500",
    tags: ["Text"],
  },
  {
    id: "markdown-toc-generator",
    titleKey: "Catalog.MarkdownTocGenerator.title",
    descriptionKey: "Catalog.MarkdownTocGenerator.description",
    icon: ListTree,
    href: "/tools/markdown-toc-generator",
    color: "text-sky-500",
    tags: ["Documents"],
  },
  {
    id: "binary-text-converter",
    titleKey: "Catalog.BinaryTextConverter.title",
    descriptionKey: "Catalog.BinaryTextConverter.description",
    icon: Binary,
    href: "/tools/binary-text-converter",
    color: "text-indigo-500",
    tags: ["Development"],
  },
  {
    id: "css-specificity-calculator",
    titleKey: "Catalog.CssSpecificityCalculator.title",
    descriptionKey: "Catalog.CssSpecificityCalculator.description",
    icon: Layers,
    href: "/tools/css-specificity-calculator",
    color: "text-fuchsia-500",
    tags: ["Development"],
  },
  {
    id: "color-blindness-simulator",
    titleKey: "Catalog.ColorBlindnessSimulator.title",
    descriptionKey: "Catalog.ColorBlindnessSimulator.description",
    icon: Eye,
    href: "/tools/color-blindness-simulator",
    color: "text-violet-500",
    tags: ["Image"],
  },
  {
    id: "countdown-timer",
    titleKey: "Catalog.CountdownTimer.title",
    descriptionKey: "Catalog.CountdownTimer.description",
    icon: Timer,
    href: "/tools/countdown-timer",
    color: "text-orange-500",
    tags: ["Utilities"],
  },
  {
    id: "barcode-generator",
    titleKey: "Catalog.BarcodeGenerator.title",
    descriptionKey: "Catalog.BarcodeGenerator.description",
    icon: ScanBarcode,
    href: "/tools/barcode-generator",
    color: "text-cyan-500",
    tags: ["Utilities"],
  },
  {
    id: "og-preview",
    titleKey: "Catalog.OgPreview.title",
    descriptionKey: "Catalog.OgPreview.description",
    icon: Share2,
    href: "/tools/og-preview",
    color: "text-sky-500",
    tags: ["Web"],
  },
  {
    id: "htpasswd-generator",
    titleKey: "Catalog.HtpasswdGenerator.title",
    descriptionKey: "Catalog.HtpasswdGenerator.description",
    icon: KeyRound,
    href: "/tools/htpasswd-generator",
    color: "text-emerald-500",
    tags: ["Security"],
  },
  {
    id: "cron-next-runs",
    titleKey: "Catalog.CronNextRuns.title",
    descriptionKey: "Catalog.CronNextRuns.description",
    icon: CalendarClock,
    href: "/tools/cron-next-runs",
    color: "text-sky-500",
    tags: ["Development"],
  },
  {
    id: "json-path-finder",
    titleKey: "Catalog.JsonPathFinder.title",
    descriptionKey: "Catalog.JsonPathFinder.description",
    icon: Braces,
    href: "/tools/json-path-finder",
    color: "text-emerald-500",
    tags: ["Data"],
  },
  {
    id: "video-to-gif",
    titleKey: "Catalog.VideoToGif.title",
    descriptionKey: "Catalog.VideoToGif.description",
    icon: Film,
    href: "/tools/video-to-gif",
    color: "text-pink-500",
    tags: ["Video"],
  },
  {
    id: "video-trimmer",
    titleKey: "Catalog.VideoTrimmer.title",
    descriptionKey: "Catalog.VideoTrimmer.description",
    icon: Scissors,
    href: "/tools/video-trimmer",
    color: "text-orange-500",
    tags: ["Video"],
  },
  {
    id: "video-compressor",
    titleKey: "Catalog.VideoCompressor.title",
    descriptionKey: "Catalog.VideoCompressor.description",
    icon: Minimize2,
    href: "/tools/video-compressor",
    color: "text-rose-500",
    tags: ["Video"],
  },
  {
    id: "audio-converter",
    titleKey: "Catalog.AudioConverter.title",
    descriptionKey: "Catalog.AudioConverter.description",
    icon: AudioLines,
    href: "/tools/audio-converter",
    color: "text-purple-500",
    tags: ["Audio"],
  },
  {
    id: "audio-extractor",
    titleKey: "Catalog.AudioExtractor.title",
    descriptionKey: "Catalog.AudioExtractor.description",
    icon: FileAudio,
    href: "/tools/audio-extractor",
    color: "text-fuchsia-500",
    tags: ["Audio"],
  },
  {
    id: "video-rotate",
    titleKey: "Catalog.VideoRotate.title",
    descriptionKey: "Catalog.VideoRotate.description",
    icon: RotateCw,
    href: "/tools/video-rotate",
    color: "text-rose-500",
    tags: ["Video"],
  },
  {
    id: "video-speed",
    titleKey: "Catalog.VideoSpeed.title",
    descriptionKey: "Catalog.VideoSpeed.description",
    icon: Gauge,
    href: "/tools/video-speed",
    color: "text-amber-500",
    tags: ["Video"],
  },
  {
    id: "video-resizer",
    titleKey: "Catalog.VideoResizer.title",
    descriptionKey: "Catalog.VideoResizer.description",
    icon: Scaling,
    href: "/tools/video-resizer",
    color: "text-cyan-500",
    tags: ["Video"],
  },
  {
    id: "video-crop",
    titleKey: "Catalog.VideoCrop.title",
    descriptionKey: "Catalog.VideoCrop.description",
    icon: Crop,
    href: "/tools/video-crop",
    color: "text-orange-500",
    tags: ["Video"],
  },
  {
    id: "video-merger",
    titleKey: "Catalog.VideoMerger.title",
    descriptionKey: "Catalog.VideoMerger.description",
    icon: Combine,
    href: "/tools/video-merger",
    color: "text-fuchsia-500",
    tags: ["Video"],
  },
  {
    id: "gif-to-video",
    titleKey: "Catalog.GifToVideo.title",
    descriptionKey: "Catalog.GifToVideo.description",
    icon: Video,
    href: "/tools/gif-to-video",
    color: "text-red-500",
    tags: ["Video"],
  },
  {
    id: "video-reverse",
    titleKey: "Catalog.VideoReverse.title",
    descriptionKey: "Catalog.VideoReverse.description",
    icon: Rewind,
    href: "/tools/video-reverse",
    color: "text-violet-500",
    tags: ["Video"],
  },
  {
    id: "video-mute",
    titleKey: "Catalog.VideoMute.title",
    descriptionKey: "Catalog.VideoMute.description",
    icon: VolumeX,
    href: "/tools/video-mute",
    color: "text-sky-500",
    tags: ["Video"],
  },
  {
    id: "video-frames",
    titleKey: "Catalog.VideoFrames.title",
    descriptionKey: "Catalog.VideoFrames.description",
    icon: Images,
    href: "/tools/video-frames",
    color: "text-yellow-500",
    tags: ["Video"],
  },
  {
    id: "3d-viewer",
    titleKey: "Catalog.Basic3dViewer.title",
    descriptionKey: "Catalog.Basic3dViewer.description",
    icon: Box,
    href: "/tools/3d-viewer",
    color: "text-purple-500",
    tags: ["Video"],
  },
  {
    id: "youtube-downloader",
    titleKey: "Catalog.YouTubeDownloader.title",
    descriptionKey: "Catalog.YouTubeDownloader.description",
    icon: YouTubeIcon,
    href: "/tools/youtube-downloader",
    color: "text-red-500",
    tags: ["Video"],
    // Hidden from public listings: server-side yt-dlp extraction is blocked by
    // YouTube's bot check on this datacenter IP (no free, low-risk workaround).
    // Code/route kept intact — delete this flag to re-list if a proxy is added.
    hidden: true,
  },
  {
    id: "youtube-thumbnail",
    titleKey: "Catalog.YoutubeThumbnail.title",
    descriptionKey: "Catalog.YoutubeThumbnail.description",
    icon: YouTubeIcon,
    href: "/tools/youtube-thumbnail",
    color: "text-pink-500",
    tags: ["Image"],
  },
  {
    id: "aes-crypto",
    titleKey: "Catalog.AesCrypto.title",
    descriptionKey: "Catalog.AesCrypto.description",
    icon: Lock,
    href: "/tools/aes-crypto",
    color: "text-emerald-500",
    tags: ["Security"],
  },
  {
    id: "bcrypt-generator",
    titleKey: "Catalog.BcryptGenerator.title",
    descriptionKey: "Catalog.BcryptGenerator.description",
    icon: LockKeyhole,
    href: "/tools/bcrypt-generator",
    color: "text-cyan-500",
    tags: ["Security"],
  },
  {
    id: "hmac-generator",
    titleKey: "Catalog.HmacGenerator.title",
    descriptionKey: "Catalog.HmacGenerator.description",
    icon: BadgeCheck,
    href: "/tools/hmac-generator",
    color: "text-blue-500",
    tags: ["Security"],
  },
  {
    id: "rsa-generator",
    titleKey: "Catalog.RsaGenerator.title",
    descriptionKey: "Catalog.RsaGenerator.description",
    icon: Key,
    href: "/tools/rsa-generator",
    color: "text-yellow-500",
    tags: ["Security"],
  },
  {
    id: "hash-generator",
    titleKey: "Catalog.HashGenerator.title",
    descriptionKey: "Catalog.HashGenerator.description",
    icon: Hash,
    href: "/tools/hash-generator",
    color: "text-rose-500",
    tags: ["Security"],
  },
  {
    id: "uuid-generator",
    titleKey: "Catalog.UuidGenerator.title",
    descriptionKey: "Catalog.UuidGenerator.description",
    icon: Dices,
    href: "/tools/uuid-generator",
    color: "text-violet-500",
    tags: ["Development"],
  },
  {
    id: "password-generator",
    titleKey: "Catalog.PasswordGenerator.title",
    descriptionKey: "Catalog.PasswordGenerator.description",
    icon: Shield,
    href: "/tools/password-generator",
    color: "text-green-600",
    tags: ["Security"],
  },
  {
    id: "totp-generator",
    titleKey: "Catalog.TotpGenerator.title",
    descriptionKey: "Catalog.TotpGenerator.description",
    icon: Fingerprint,
    href: "/tools/totp-generator",
    color: "text-blue-600",
    tags: ["Security"],
  },
  {
    id: "unix-timestamp",
    titleKey: "Catalog.UnixTimestamp.title",
    descriptionKey: "Catalog.UnixTimestamp.description",
    icon: Timer,
    href: "/tools/unix-timestamp",
    color: "text-amber-600",
    tags: ["Development"],
  },
  {
    id: "meta-tag-generator",
    titleKey: "Catalog.MetaTagGenerator.title",
    descriptionKey: "Catalog.MetaTagGenerator.description",
    icon: Tags,
    href: "/tools/meta-tag-generator",
    color: "text-blue-600",
    tags: ["Web"],
  },
  {
    id: "robots-txt-generator",
    titleKey: "Catalog.RobotsTxtGenerator.title",
    descriptionKey: "Catalog.RobotsTxtGenerator.description",
    icon: Bot,
    href: "/tools/robots-txt-generator",
    color: "text-gray-600",
    tags: ["Web"],
  },
  {
    id: "sitemap-generator",
    titleKey: "Catalog.SitemapGenerator.title",
    descriptionKey: "Catalog.SitemapGenerator.description",
    icon: MapIcon,
    href: "/tools/sitemap-generator",
    color: "text-green-600",
    tags: ["Web"],
  },
  {
    id: "color-converter",
    titleKey: "Catalog.ColorConverter.title",
    descriptionKey: "Catalog.ColorConverter.description",
    icon: Palette,
    href: "/tools/color-converter",
    color: "text-pink-600",
    tags: ["Design"],
  },
  {
    id: "subnet-calculator",
    titleKey: "Catalog.SubnetCalculator.title",
    descriptionKey: "Catalog.SubnetCalculator.description",
    icon: Network,
    href: "/tools/subnet-calculator",
    color: "text-cyan-600",
    tags: ["Utilities"],
  },
  {
    id: "css-minifier",
    titleKey: "Catalog.CssMinifier.title",
    descriptionKey: "Catalog.CssMinifier.description",
    icon: FileCode2,
    href: "/tools/css-minifier",
    color: "text-teal-500",
    tags: ["Development"],
  },
  {
    id: "json-ld-generator",
    titleKey: "Catalog.JsonLdGenerator.title",
    descriptionKey: "Catalog.JsonLdGenerator.description",
    icon: Braces,
    href: "/tools/json-ld-generator",
    color: "text-amber-600",
    tags: ["Web"],
  },
  {
    id: "env-editor",
    titleKey: "Catalog.EnvEditor.title",
    descriptionKey: "Catalog.EnvEditor.description",
    icon: FileText,
    href: "/tools/env-editor",
    color: "text-gray-500",
    tags: ["Development"],
  },
  {
    id: "toml-converter",
    titleKey: "Catalog.TomlConverter.title",
    descriptionKey: "Catalog.TomlConverter.description",
    icon: FileJson,
    href: "/tools/toml-converter",
    color: "text-orange-600",
    tags: ["Data"],
  },
  {
    id: "http-header-analyzer",
    titleKey: "Catalog.HttpHeaderAnalyzer.title",
    descriptionKey: "Catalog.HttpHeaderAnalyzer.description",
    icon: Activity,
    href: "/tools/http-header-analyzer",
    color: "text-blue-500",
    tags: ["Web"],
  },
  {
    id: "seo-analyzer",
    titleKey: "Catalog.SeoAnalyzer.title",
    descriptionKey: "Catalog.SeoAnalyzer.description",
    icon: Search,
    href: "/tools/seo-analyzer",
    color: "text-emerald-500",
    tags: ["Web"],
  },
  {
    id: "webhook-tester",
    titleKey: "Catalog.WebhookTester.title",
    descriptionKey: "Catalog.WebhookTester.description",
    icon: Webhook,
    href: "/tools/webhook-tester",
    color: "text-purple-600",
    tags: ["Web"],
  },
  {
    id: "git-diff-viewer",
    titleKey: "Catalog.GitDiffViewer.title",
    descriptionKey: "Catalog.GitDiffViewer.description",
    icon: GitCompareArrows,
    href: "/tools/git-diff-viewer",
    color: "text-orange-600",
    tags: ["Development"],
  },
  {
    id: "exif-viewer",
    titleKey: "Catalog.ExifViewer.title",
    descriptionKey: "Catalog.ExifViewer.description",
    icon: Camera,
    href: "/tools/exif-viewer",
    color: "text-rose-500",
    tags: ["Image"],
  },
  {
    id: "image-resizer",
    titleKey: "Catalog.ImageResizer.title",
    descriptionKey: "Catalog.ImageResizer.description",
    icon: Scaling,
    href: "/tools/image-resizer",
    color: "text-indigo-500",
    tags: ["Image"],
  },
  {
    id: "svg-optimizer",
    titleKey: "Catalog.SvgOptimizer.title",
    descriptionKey: "Catalog.SvgOptimizer.description",
    icon: Shrink,
    href: "/tools/svg-optimizer",
    color: "text-emerald-600",
    tags: ["Design"],
  },
  {
    id: "svg-visualizer",
    titleKey: "Catalog.SvgVisualizer.title",
    descriptionKey: "Catalog.SvgVisualizer.description",
    icon: PenTool,
    href: "/tools/svg-visualizer",
    color: "text-indigo-500",
    tags: ["Design"],
  },
  {
    id: "screenshot-beautifier",
    titleKey: "Catalog.ScreenshotBeautifier.title",
    descriptionKey: "Catalog.ScreenshotBeautifier.description",
    icon: MonitorSmartphone,
    href: "/tools/screenshot-beautifier",
    color: "text-violet-500",
    tags: ["Design"],
  },
  {
    id: "text-to-speech",
    titleKey: "Catalog.TextToSpeech.title",
    descriptionKey: "Catalog.TextToSpeech.description",
    icon: Volume2,
    href: "/tools/text-to-speech",
    color: "text-blue-600",
    tags: ["Audio"],
  },
  {
    id: "whois-lookup",
    titleKey: "Catalog.WhoisLookup.title",
    descriptionKey: "Catalog.WhoisLookup.description",
    icon: Globe2,
    href: "/tools/whois-lookup",
    color: "text-teal-600",
    tags: ["Utilities"],
  },
  {
    id: "image-eraser",
    titleKey: "Catalog.ImageEraser.title",
    descriptionKey: "Catalog.ImageEraser.description",
    icon: Eraser,
    href: "/tools/image-eraser",
    color: "text-fuchsia-500",
    tags: ["Image", "AI"],
  },
  {
    id: "image-watermark",
    titleKey: "Catalog.ImageWatermark.title",
    descriptionKey: "Catalog.ImageWatermark.description",
    icon: Droplets,
    href: "/tools/image-watermark",
    color: "text-cyan-500",
    tags: ["Image"],
  },
  {
    id: "image-filters",
    titleKey: "Catalog.ImageFilters.title",
    descriptionKey: "Catalog.ImageFilters.description",
    icon: SlidersHorizontal,
    href: "/tools/image-filters",
    color: "text-amber-500",
    tags: ["Image"],
  },
  {
    id: "collage-maker",
    titleKey: "Catalog.CollageMaker.title",
    descriptionKey: "Catalog.CollageMaker.description",
    icon: LayoutGrid,
    href: "/tools/collage-maker",
    color: "text-pink-500",
    tags: ["Image"],
  },
  {
    id: "images-to-ppt",
    titleKey: "Catalog.ImagesToPpt.title",
    descriptionKey: "Catalog.ImagesToPpt.description",
    icon: Presentation,
    href: "/tools/images-to-ppt",
    color: "text-orange-500",
    tags: ["Image"],
  },
  {
    id: "meme-generator",
    titleKey: "Catalog.MemeGenerator.title",
    descriptionKey: "Catalog.MemeGenerator.description",
    icon: Smile,
    href: "/tools/meme-generator",
    color: "text-yellow-500",
    tags: ["Image"],
  },
  {
    id: "color-picker",
    titleKey: "Catalog.ColorPicker.title",
    descriptionKey: "Catalog.ColorPicker.description",
    icon: Pipette,
    href: "/tools/color-picker",
    color: "text-violet-500",
    tags: ["Design"],
  },
  {
    id: "markdown-to-pdf",
    titleKey: "Catalog.MarkdownToPdf.title",
    descriptionKey: "Catalog.MarkdownToPdf.description",
    icon: FileDown,
    href: "/tools/markdown-to-pdf",
    color: "text-blue-500",
    tags: ["Utilities"],
  },
  {
    id: "csv-editor",
    titleKey: "Catalog.CsvEditor.title",
    descriptionKey: "Catalog.CsvEditor.description",
    icon: Table,
    href: "/tools/csv-editor",
    color: "text-green-500",
    tags: ["Utilities"],
  },
  {
    id: "code-formatter",
    titleKey: "Catalog.CodeFormatter.title",
    descriptionKey: "Catalog.CodeFormatter.description",
    icon: Code2,
    href: "/tools/code-formatter",
    color: "text-indigo-500",
    tags: ["Development"],
  },
  {
    id: "pomodoro-timer",
    titleKey: "Catalog.PomodoroTimer.title",
    descriptionKey: "Catalog.PomodoroTimer.description",
    icon: TimerReset,
    href: "/tools/pomodoro-timer",
    color: "text-rose-500",
    tags: ["Utilities"],
  },
  {
    id: "lorem-ipsum",
    titleKey: "Catalog.LoremIpsum.title",
    descriptionKey: "Catalog.LoremIpsum.description",
    icon: Pilcrow,
    href: "/tools/lorem-ipsum",
    color: "text-amber-500",
    tags: ["Text"],
  },
  {
    id: "gitignore-generator",
    titleKey: "Catalog.GitignoreGenerator.title",
    descriptionKey: "Catalog.GitignoreGenerator.description",
    icon: GitBranch,
    href: "/tools/gitignore-generator",
    color: "text-orange-500",
    tags: ["Development"],
  },
  {
    id: "cubic-bezier",
    titleKey: "Catalog.CubicBezier.title",
    descriptionKey: "Catalog.CubicBezier.description",
    icon: Spline,
    href: "/tools/cubic-bezier",
    color: "text-violet-500",
    tags: ["Design"],
  },
  {
    id: "color-contrast-checker",
    titleKey: "Catalog.ColorContrastChecker.title",
    descriptionKey: "Catalog.ColorContrastChecker.description",
    icon: Contrast,
    href: "/tools/color-contrast-checker",
    color: "text-emerald-500",
    tags: ["Design"],
  },
  {
    id: "aspect-ratio-calculator",
    titleKey: "Catalog.AspectRatioCalculator.title",
    descriptionKey: "Catalog.AspectRatioCalculator.description",
    icon: Proportions,
    href: "/tools/aspect-ratio-calculator",
    color: "text-sky-500",
    tags: ["Design"],
  },
  {
    id: "css-clamp-generator",
    titleKey: "Catalog.CssClampGenerator.title",
    descriptionKey: "Catalog.CssClampGenerator.description",
    icon: Type,
    href: "/tools/css-clamp-generator",
    color: "text-violet-500",
    tags: ["Design"],
  },
  {
    id: "roman-numeral-converter",
    titleKey: "Catalog.RomanNumeralConverter.title",
    descriptionKey: "Catalog.RomanNumeralConverter.description",
    icon: Hash,
    href: "/tools/roman-numeral-converter",
    color: "text-amber-500",
    tags: ["Utilities"],
  },
  {
    id: "text-repeater",
    titleKey: "Catalog.TextRepeater.title",
    descriptionKey: "Catalog.TextRepeater.description",
    icon: Repeat,
    href: "/tools/text-repeater",
    color: "text-rose-500",
    tags: ["Text"],
  },
  {
    id: "mock-data-generator",
    titleKey: "Catalog.MockDataGenerator.title",
    descriptionKey: "Catalog.MockDataGenerator.description",
    icon: Database,
    href: "/tools/mock-data-generator",
    color: "text-indigo-500",
    tags: ["Development"],
  },
  {
    id: "html-minifier",
    titleKey: "Catalog.HtmlMinifier.title",
    descriptionKey: "Catalog.HtmlMinifier.description",
    icon: Minimize2,
    href: "/tools/html-minifier",
    color: "text-orange-500",
    tags: ["Development"],
  },
  {
    id: "ai-token-counter",
    titleKey: "Catalog.AiTokenCounter.title",
    descriptionKey: "Catalog.AiTokenCounter.description",
    icon: Cpu,
    href: "/tools/ai-token-counter",
    color: "text-purple-500",
    tags: ["AI","Development"],
  },
  {
    id: "prompt-optimizer",
    titleKey: "Catalog.PromptOptimizer.title",
    descriptionKey: "Catalog.PromptOptimizer.description",
    icon: Wand2,
    href: "/tools/prompt-optimizer",
    color: "text-indigo-500",
    tags: ["AI","Development"],
  },
  {
    id: "tailwind-config-builder",
    titleKey: "Catalog.TailwindConfigBuilder.title",
    descriptionKey: "Catalog.TailwindConfigBuilder.description",
    icon: Settings,
    href: "/tools/tailwind-config-builder",
    color: "text-cyan-500",
    tags: ["Design","Development"],
  },
  {
    id: "css-grid-generator",
    titleKey: "Catalog.CssGridGenerator.title",
    descriptionKey: "Catalog.CssGridGenerator.description",
    icon: LayoutGrid,
    href: "/tools/css-grid-generator",
    color: "text-emerald-500",
    tags: ["Design"],
  },
  {
    id: "svg-shapes-generator",
    titleKey: "Catalog.SvgShapesGenerator.title",
    descriptionKey: "Catalog.SvgShapesGenerator.description",
    icon: Spline,
    href: "/tools/svg-shapes-generator",
    color: "text-amber-500",
    tags: ["Design"],
  },
  {
    id: "mesh-gradient-generator",
    titleKey: "Catalog.MeshGradientGenerator.title",
    descriptionKey: "Catalog.MeshGradientGenerator.description",
    icon: Palette,
    href: "/tools/mesh-gradient-generator",
    color: "text-fuchsia-500",
    tags: ["Design"],
  },
  {
    id: "font-pairer",
    titleKey: "Catalog.FontPairer.title",
    descriptionKey: "Catalog.FontPairer.description",
    icon: Type,
    href: "/tools/font-pairer",
    color: "text-rose-500",
    tags: ["Design"],
  },
  {
    id: "docker-compose-generator",
    titleKey: "Catalog.DockerComposeGenerator.title",
    descriptionKey: "Catalog.DockerComposeGenerator.description",
    icon: Package,
    href: "/tools/docker-compose-generator",
    color: "text-blue-500",
    tags: ["Development"],
  },
  {
    id: "git-commit-helper",
    titleKey: "Catalog.GitCommitHelper.title",
    descriptionKey: "Catalog.GitCommitHelper.description",
    icon: GitCommit,
    href: "/tools/git-commit-helper",
    color: "text-gray-500",
    tags: ["Development"],
  },
  {
    id: "json-schema-generator",
    titleKey: "Catalog.JsonSchemaGenerator.title",
    descriptionKey: "Catalog.JsonSchemaGenerator.description",
    icon: Braces,
    href: "/tools/json-schema-generator",
    color: "text-emerald-600",
    tags: ["Data","Development"],
  },
  {
    id: "url-parser",
    titleKey: "Catalog.UrlParser.title",
    descriptionKey: "Catalog.UrlParser.description",
    icon: Link,
    href: "/tools/url-parser",
    color: "text-sky-500",
    tags: ["Web"],
  },
  {
    id: "http-status-codes",
    titleKey: "Catalog.HttpStatusCodes.title",
    descriptionKey: "Catalog.HttpStatusCodes.description",
    icon: Globe,
    href: "/tools/http-status-codes",
    color: "text-indigo-600",
    tags: ["Web"],
  },
  {
    id: "cors-configurator",
    titleKey: "Catalog.CorsConfigurator.title",
    descriptionKey: "Catalog.CorsConfigurator.description",
    icon: Shield,
    href: "/tools/cors-configurator",
    color: "text-emerald-700",
    tags: ["Web","Security"],
  },
  {
    id: "markdown-table-builder",
    titleKey: "Catalog.MarkdownTableBuilder.title",
    descriptionKey: "Catalog.MarkdownTableBuilder.description",
    icon: Table,
    href: "/tools/markdown-table-builder",
    color: "text-slate-600",
    tags: ["Documents"],
  },
  {
    id: "ascii-art-diagram",
    titleKey: "Catalog.AsciiArtDiagram.title",
    descriptionKey: "Catalog.AsciiArtDiagram.description",
    icon: Terminal,
    href: "/tools/ascii-art-diagram",
    color: "text-gray-600",
    tags: ["Design","Development"],
  },
  {
    id: "budget-planner",
    titleKey: "Catalog.BudgetPlanner.title",
    descriptionKey: "Catalog.BudgetPlanner.description",
    icon: TrendingUp,
    href: "/tools/budget-planner",
    color: "text-green-500",
    tags: ["Finance"],
  },
  {
    id: "kr-word-counter",
    titleKey: "Catalog.KrWordCounter.title",
    descriptionKey: "Catalog.KrWordCounter.description",
    icon: CaseSensitive,
    href: "/tools/kr-word-counter",
    color: "text-amber-500",
    tags: ["Text","Korea"],
  },
  {
    id: "kr-id-validator",
    titleKey: "Catalog.KrIdValidator.title",
    descriptionKey: "Catalog.KrIdValidator.description",
    icon: BadgeCheck,
    href: "/tools/kr-id-validator",
    color: "text-emerald-500",
    tags: ["Utilities","Korea"],
  },
  {
    id: "kr-real-estate",
    titleKey: "Catalog.KrRealEstate.title",
    descriptionKey: "Catalog.KrRealEstate.description",
    icon: Home,
    href: "/tools/kr-real-estate",
    color: "text-blue-600",
    tags: ["Finance","Korea"],
  },
];

export function getToolById(id: string) {
  return toolsCatalog.find(
    (tool) => tool.id === id || tool.href.endsWith(`/${id}`),
  );
}
